name: CasC Pipeline
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  casc:
    uses: aap-casc-platform-demo/aap-casc-engine/.github/workflows/casc-validate-and-trigger.yml@main
    with:
      dispatcher_jt_name: jt-platform-casc_dispatcher
    secrets: inherit
